# Generated by Django 6.0.1 on 2026-04-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeon', '0002_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
