# Generated by Django 6.0.1 on 2026-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeon', '0003_delete_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Image shown on mobile devices', null=True, upload_to='hero/mobile/'),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/hover/'),
        ),
    ]
